# Generated by Django 5.1.1 on 2024-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_laporankerusakan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankerusakan',
            name='provinsi',
            field=models.CharField(choices=[('Aceh', 'Aceh'), ('Bali', 'Bali'), ('Banten', 'Banten'), ('Bengkulu', 'Bengkulu'), ('DI Yogyakarta', 'DI Yogyakarta'), ('DKI Jakarta', 'DKI Jakarta'), ('Gorontalo', 'Gorontalo'), ('Jambi', 'Jambi'), ('Jawa Barat', 'Jawa Barat'), ('Jawa Tengah', 'Jawa Tengah'), ('Jawa Timur', 'Jawa Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Lampung', 'Lampung'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Papua', 'Papua'), ('Papua Barat', 'Papua Barat'), ('Riau', 'Riau'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Sumatera Barat', 'Sumatera Barat'), ('Sumatera Selatan', 'Sumatera Selatan'), ('Sumatera Utara', 'Sumatera Utara')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JadwalPekerjaan',
        ),
    ]
