# Generated by Django 5.1.1 on 2024-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0003_laporankerusakan_provinsi_delete_jadwalpekerjaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporankerusakan',
            name='provinsi',
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='kota',
            field=models.CharField(choices=[('Palembang', 'Palembang'), ('Bengkulu', 'Bengkulu'), ('Bandar Lampung', 'Bandar Lampung'), ('Pangkal Pinang', 'Pangkal Pinang'), ('Padang', 'Padang'), ('Pekanbaru', 'Pekanbaru'), ('Jambi', 'Jambi'), ('Batam', 'Batam'), ('Medan', 'Medan'), ('Banda Aceh', 'Banda Aceh'), ('Surabaya', 'Surabaya'), ('Semarang', 'Semarang'), ('Yogyakarta', 'Yogyakarta'), ('Bandung', 'Bandung'), ('Serang', 'Serang'), ('Jakarta', 'Jakarta'), ('Banjarmasin', 'Banjarmasin'), ('Samarinda', 'Samarinda'), ('Palangkaraya', 'Palangkaraya'), ('Pontianak', 'Pontianak'), ('Tarakan', 'Tarakan'), ('Makassar', 'Makassar'), ('Manado', 'Manado'), ('Palu', 'Palu'), ('Kendari', 'Kendari'), ('Mamuju', 'Mamuju'), ('Ambon', 'Ambon'), ('Jayapura', 'Jayapura'), ('Manokwari', 'Manokwari'), ('Gorontalo', 'Gorontalo'), ('Ternate', 'Ternate'), ('Denpasar', 'Denpasar'), ('Mataram', 'Mataram'), ('Kupang', 'Kupang'), ('Cirebon', 'Cirebon'), ('Lhokseumawe', 'Lhokseumawe'), ('Pematang Siantar', 'Pematang Siantar'), ('Sibolga', 'Sibolga'), ('Malang', 'Malang'), ('Kediri', 'Kediri'), ('Jember', 'Jember'), ('Solo', 'Solo'), ('Purwokerto', 'Purwokerto'), ('Tegal', 'Tegal'), ('Tasikmalaya', 'Tasikmalaya'), ('Balikpapan', 'Balikpapan')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
